name: Remote SSH
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd {{ secrets.PRODUCTION_FOLDER }}
          ${{ secrets.SCRIPT }}
          sudo systemctl restart apache2
